### PR TITLE
Issue #9 - Validating if _notifications is null, and initializing it

### PR DESCRIPTION
**Pull request by Brunogr**
in some cases the class is created by reflection and _notifications is not instantiated on constructor.

### CODE REVIEW

**Comment by andrebaltieri** [comment]
Hi Bruno, can you please provide some samples?

**Comment by Brunogr** [comment]
ok, i'll prepare an example using mongoDB Driver and i'll send you

**Comment by carloscpossa** [comment]
Hi, Bruno!

I am using Flunt with MongoDb Driver and i don't have problem. However, the constructors of my classes (entities, value objects, ...) extends the constructors of the base class (Notifiable).

**Comment by andrebaltieri** [comment]
Closing the issue since no more information was provided!

**Pull request closed without merging**
